// Generated by CoffeeScript 2.5.1
var APN_PROVIDER_OPTS, apn, apnProvider;

apn = require("apn");

APN_PROVIDER_OPTS = {
  token: {
    key: Assets.absoluteFilePath("key.p8"),
    keyId: "88HW4KSBHX",
    teamId: "FW2A52D3L8"
  },
  production: true
};

exports._sendApnNotification = function(alert, payload, opts) {
  var note;
  // Send iOS push notification
  note = new apn.Notification();
  // Expires 1 hour from now.
  note.alert = alert;
  note.payload = payload;
  note.expiry = opts.expiry;
  note.badge = opts.badge;
  note.sound = opts.sound;
  note.topic = opts.topic;
  // Returns a promise
  return apnProvider().send(note, user.iOSRegistrationID);
};

apnProvider = function() {
  if (apnProvider.__memo == null) {
    apnProvider.__memo = new apn.Provider(APN_PROVIDER_OPTS);
  }
  return apnProvider.__memo;
};
