// Generated by CoffeeScript 2.5.1
var FCM, fcmKey, fcmProvider;

FCM = require("fcm-node");

fcmKey = require("../../../../../../key.json");

fcmProvider = function() {
  if (exports.fcmProvider.__memo == null) {
    fcmProvider.__memo = new FCM(fcmKey);
  }
  return fcmProvider.__memo;
};

exports._sendFcmNotification = function(registrationID, alert, opts, payload) {
  var fcm, message;
  fcm = fcmProvider();
  payload.title = alert.title;
  payload.message = alert.msg;
  payload.badge = opts.badge;
  payload.style = opts.style;
  payload.summaryText = opts.summaryText;
  message = {
    to: registrationID,
    data: payload
  };
  return new Promise(function(res, rej) {
    return fcm.send(message, function(err, r) {
      if (err != null) {
        return rej(err);
      } else {
        return res(r);
      }
    });
  });
};
